use super::*;

// ── Dataset hierarchy ──────────────────────────────────────────────

/// A whole-slide image file (or set of files for DICOM).
#[derive(Debug)]
pub struct Dataset {
    pub id: DatasetId,
    pub scenes: Vec<Scene>,
    pub associated_images: HashMap<String, AssociatedImage>,
    pub properties: Properties,
    pub icc_profiles: HashMap<(usize, usize), Vec<u8>>,
}

/// A distinct scan region within a dataset.
#[derive(Debug)]
pub struct Scene {
    pub id: String,
    pub name: Option<String>,
    pub series: Vec<Series>,
}

/// A coherent image pyramid sharing the same axes and sample type.
#[derive(Debug)]
pub struct Series {
    pub id: String,
    pub axes: AxesShape,
    pub levels: Vec<Level>,
    pub sample_type: SampleType,
    pub channels: Vec<ChannelInfo>,
}

/// Axis extents beyond x/y. Default is 2D (z=1, c=1, t=1).
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub struct AxesShape {
    pub z: u32,
    pub c: u32,
    pub t: u32,
}

impl Default for AxesShape {
    fn default() -> Self {
        Self { z: 1, c: 1, t: 1 }
    }
}

/// One resolution level in a pyramid.
#[derive(Debug)]
pub struct Level {
    pub dimensions: (u64, u64),
    pub downsample: f64,
    pub tile_layout: TileLayout,
}

/// Whether a pyramid level is backed by source pixels or generated by the reader.
#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
pub enum LevelSourceKind {
    /// The level has pixel data backed directly by the source dataset.
    Physical,
    /// The level is synthesized by downsampling another level.
    SyntheticDownsample,
}
// ── Channel / Associated image metadata ────────────────────────────

#[derive(Debug, Clone)]
pub struct ChannelInfo {
    pub name: Option<String>,
    pub color: Option<[u8; 3]>,
    pub excitation_nm: Option<f64>,
    pub emission_nm: Option<f64>,
}

/// Metadata for an associated image (label, macro, thumbnail).
#[derive(Debug, Clone)]
pub struct AssociatedImage {
    pub dimensions: (u32, u32),
    pub sample_type: SampleType,
    pub channels: u16,
}

// ── Identity / Compression ─────────────────────────────────────────

/// Unique identity for cache keying. 128-bit to avoid truncation collisions.
#[derive(Clone, Copy, Hash, Eq, PartialEq, Debug)]
pub struct DatasetId(pub u128);

/// Stable index into `Dataset::scenes`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub struct SceneId(pub usize);

/// Stable index into `Scene::series`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub struct SeriesId(pub usize);

/// Stable index into `Series::levels`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub struct LevelIdx(pub u32);

/// Plane index for multi-dimensional axes (z/c/t).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Default)]
pub struct PlaneIdx(pub PlaneSelection);

/// Compression codec for TIFF tile/strip data.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum Compression {
    None,
    Lzw,
    Deflate,
    Zstd,
    Jpeg,
    Jp2kYcbcr,
    Jp2kRgb,
    JpegLs,
    Other(u16),
}

#[derive(Debug, Clone, Copy, Default, Eq, PartialEq, Hash)]
pub enum TileCodecKind {
    Jpeg,
    Jp2k,
    Htj2k,
    #[default]
    Other,
}

impl TileCodecKind {
    pub fn from_compression(compression: Compression) -> Self {
        match compression {
            Compression::Jpeg => Self::Jpeg,
            Compression::Jp2kRgb | Compression::Jp2kYcbcr => Self::Jp2k,
            _ => Self::Other,
        }
    }
}

/// Photometric interpretation for an encoded tile payload.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum EncodedTilePhotometricInterpretation {
    Monochrome2,
    Rgb,
    YbrFull422,
}

/// Raw compressed tile bytes that can be copied into another container without
/// decoding pixels.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct RawCompressedTile {
    pub compression: Compression,
    pub width: u32,
    pub height: u32,
    pub bits_allocated: u16,
    pub samples_per_pixel: u16,
    pub photometric_interpretation: EncodedTilePhotometricInterpretation,
    pub data: Vec<u8>,
}
