name: publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      dry-run-only:
        description: "Run cargo publish in dry-run mode"
        type: boolean
        required: false
        default: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  DRY_RUN_ONLY: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only }}

jobs:
  publish-ziggurat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: scripts/publish-crate.sh
